config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djangocourse.urls', namespace='djangocourse'))
]

djangocourse/urls.py
from django.urls import path
from djangocourse.apps import DjangocourseConfig
from djangocourse.views import *

app_name = DjangocourseConfig.name

urlpatterns = [
    path('', DistributionListView.as_view(), name='distribution'),
    path('client/', ClientListView.as_view(), name='client'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('message/', MessageListView.as_view(), name='message'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('distribution_create/', DistributionCreateView.as_view(), name='distribution_create'),
    path('distribution_update/<int:pk>/', DistributionUpdateView.as_view(), name='distribution_update'),
    path('distribution_delete/<int:pk>/', DistributionDeleteView.as_view(), name='distribution_delete'),
]

djangocourse/models.py
import datetime

from django.db import models
from datetime import date


# Create your models here.

class Client(models.Model):
    last_name = models.CharField(max_length=250, verbose_name='Фамилия')
    first_name = models.CharField(max_length=250, verbose_name='Имя')
    middle_name = models.CharField(max_length=250, verbose_name='Отчество')
    email = models.CharField(max_length=250, verbose_name='Почта')
    comment = models.CharField(max_length=250, verbose_name='Комментарий')

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.middle_name}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    theme = models.CharField(max_length=250, verbose_name='тема')
    text = models.CharField(max_length=250, verbose_name='текст')

    def __str__(self):
        return f'{self.theme}'


class DistributionList(models.Model):
    STATUS_CREATED = 'created'
    STATUS_LAUNCHED = 'launched'
    STATUS_COMPLETED = 'completed'
    STATUSES = (
        (STATUS_CREATED, 'создано'),
        (STATUS_LAUNCHED, 'запущено'),
        (STATUS_COMPLETED, 'завершено')
    )

    PERIOD_DAY = 'day'
    PERIOD_WEEK = 'week'
    PERIOD_MONTH = 'month'
    PERIODS = (
        (PERIOD_DAY, 'день'),
        (PERIOD_WEEK, 'неделя'),
        (PERIOD_MONTH, 'месяц')
    )
    client = models.ForeignKey('Client', on_delete=models.CASCADE)
    message = models.ForeignKey('Message', on_delete=models.CASCADE)
    time = models.TimeField(null=True, verbose_name='Время рассылки')
    date = models.DateField(default=date.today(), verbose_name='Дата')
    periodicity = models.CharField(choices=PERIODS, default=PERIOD_DAY, max_length=10, verbose_name='Период')
    status = models.CharField(choices=STATUSES, default=STATUS_CREATED, max_length=10, verbose_name='Статус')

class ReportList(models.Model):
    pass

djangocourse/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from djangocourse.models import Client, Message, DistributionList


class ClientListView(ListView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    fields = ('first_name', 'last_name', 'middle_name', 'email', 'comment')
    success_url = reverse_lazy('djangocourse:client')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('djangocourse:client')


class ClientUpdateView(UpdateView):
    model = Client
    fields = ('first_name', 'last_name', 'middle_name', 'email', 'comment')
    success_url = reverse_lazy('djangocourse:client')


class MessageListView(ListView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    fields = ('theme', 'text')
    success_url = reverse_lazy('djangocourse:message')


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('djangocourse:message')


class MessageUpdateView(UpdateView):
    model = Message
    fields = ('theme', 'text')
    success_url = reverse_lazy('djangocourse:message')


class DistributionListView(ListView):
    model = DistributionList


class DistributionCreateView(CreateView):
    model = DistributionList
    fields = ('__all__')
    success_url = reverse_lazy('djangocourse:distribution')


class DistributionUpdateView(UpdateView):
    model = DistributionList
    fields = ('__all__')
    success_url = reverse_lazy('djangocourse:distribution')


class DistributionDeleteView(DeleteView):
    model = DistributionList
    success_url = reverse_lazy('djangocourse:distribution')

djangocourse/templates/djangocourse/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'djangocourse/includes/inc_main_menu.html' %}
<head>
    <meta charset="UTF-8">
    <title>Рассылка</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% block content %}
{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

djangocourse/templates/djangocourse/client_confirm_delete.html
{% extends 'djangocourse/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p><h5> Вы действительно хотите удалить статью {{object.name}}? </h5></p>
                <a class="p-2 btn btn-primary"
                   href="{% url 'djangocourse:client' %}">Отменить</a>
                <button class="p-2 btn btn-danger" type="submit">Удалить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangocourse/templates/djangocourse/client_form.html
{% extends 'djangocourse/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangocourse/templates/djangocourse/client_list.html
{% extends 'djangocourse/base.html' %}
{% block content %}
<div class="container">
    <table class="table caption-top">
        <caption>Клиенты</caption>
        <thead>
        <tr>
            <th scope="col">Фамилия</th>
            <th scope="col">Имя</th>
            <th scope="col">Отчество</th>
            <th scope="col">Email</th>
            <th scope="col">Комментарий</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{object.first_name}}</td>
            <td>{{object.last_name}}</td>
            <td>{{object.middle_name}}</td>
            <td>{{object.email}}</td>
            <td>{{object.comment}}</td>
            <td>
                <a class="p-1 btn btn-primary" href="{% url 'djangocourse:client_update' object.pk %}">Редактировать</a>
                <a class="p-1 btn btn-danger" href="{% url 'djangocourse:client_delete' object.pk %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

djangocourse/templates/djangocourse/distributionlist_confirm_delete.html
{% extends 'djangocourse/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p><h5> Вы действительно хотите удалить рассылку? </h5></p>
                <a class="p-2 btn btn-primary"
                   href="{% url 'djangocourse:distribution' %}">Отменить</a>
                <button class="p-2 btn btn-danger" type="submit">Удалить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangocourse/templates/djangocourse/distributionlist_form.html
{% extends 'djangocourse/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangocourse/templates/djangocourse/distributionlist_list.html
{% extends 'djangocourse/base.html' %}
{% block content %}
<div class="container">
    <table class="table caption-top">
        <caption>Рассылки</caption>
        <thead>
        <tr>
            <th scope="col">Клиент</th>
            <th scope="col">Тема</th>
            <th scope="col">Время</th>
            <th scope="col">Периодичность</th>
            <th scope="col">Статус</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{object.client}}</td>
            <td>{{object.message}}</td>
            <td>{{object.time}}</td>
            <td>{{object.periodicity}}</td>
            <td>{{object.status}}</td>
            <td>
                <a class="p-1 btn btn-primary" href="{% url 'djangocourse:distribution_update' object.pk %}">Редактировать</a>
                <a class="p-1 btn btn-danger" href="{% url 'djangocourse:distribution_delete' object.pk %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

djangocourse/templates/djangocourse/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Рассылка</h5>
    <nav class="ms-5">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <a class="p-2 btn btn-primary" href="{% url 'djangocourse:client' %}">Главная</a>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Создать
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'djangocourse:client_create' %}">Клиента</a></li>
                    <li><a class="dropdown-item" href="{% url 'djangocourse:distribution_create' %}">Рассылку</a></li>
                    <li><a class="dropdown-item" href="{% url 'djangocourse:message_create' %}">Сообщение</a></li>
                </ul>
            </div>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Редактировать
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'djangocourse:client' %}">Клиента</a></li>
                    <li><a class="dropdown-item" href="{% url 'djangocourse:distribution' %}">Рассылку</a></li>
                    <li><a class="dropdown-item" href="{% url 'djangocourse:message' %}">Сообщение</a></li>
                </ul>
            </div>
            <button type="button" class="btn btn-primary">Отчет</button>
        </div>
    </nav>
</div>

djangocourse/templates/djangocourse/message_confirm_delete.html
{% extends 'djangocourse/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p><h5> Вы действительно хотите удалить сообщение {{object.theme}}? </h5></p>
                <a class="p-2 btn btn-primary"
                   href="{% url 'djangocourse:message' %}">Отменить</a>
                <button class="p-2 btn btn-danger" type="submit">Удалить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangocourse/templates/djangocourse/message_form.html
{% extends 'djangocourse/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangocourse/templates/djangocourse/message_list.html
{% extends 'djangocourse/base.html' %}
{% block content %}
<div class="container">
    <table class="table caption-top">
        <caption>Сообщения</caption>
        <thead>
        <tr>
            <th scope="col">Тема</th>
            <th scope="col">Текст</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{object.theme}}</td>
            <td>{{object.text}}</td>
            <td>
                <a class="p-1 btn btn-primary" href="{% url 'djangocourse:message_update' object.pk %}">Редактировать</a>
                <a class="p-1 btn btn-danger" href="{% url 'djangocourse:message_delete' object.pk %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}